"""Utility helpers: matplotlib styling, temp directories, image conversion, report templates."""

import os
import io
import tempfile
from pathlib import Path
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib import font_manager

OUTPUT_DIR = Path(__file__).parent.parent / "outputs"
TEMP_DIR = Path(tempfile.gettempdir()) / "da_app_charts"


def setup_matplotlib_style() -> None:
    """Apply a clean seaborn-inspired matplotlib style with English-safe fonts."""
    try:
    plt.style.use("seaborn-v0_8-whitegrid")
except Exception:
    try:
        plt.style.use("seaborn-whitegrid")
    except Exception:
        plt.style.use("ggplot")
    plt.rcParams.update({
        "figure.dpi": 150,
        "savefig.dpi": 150,
        "savefig.bbox": "tight",
        "savefig.pad_inches": 0.1,
        "font.size": 10,
        "axes.titlesize": 12,
        "axes.labelsize": 10,
        "font.family": "sans-serif",
        "font.sans-serif": ["Arial", "DejaVu Sans", "Helvetica", "sans-serif"],
    })


def temp_output_dir() -> Path:
    """Return (and ensure) the temporary chart output directory."""
    TEMP_DIR.mkdir(parents=True, exist_ok=True)
    return TEMP_DIR


def figure_to_png_bytes(fig: plt.Figure | None = None, dpi: int = 150) -> bytes:
    """Convert a matplotlib Figure to PNG bytes. Uses current figure if none given."""
    if fig is None:
        fig = plt.gcf()
    buf = io.BytesIO()
    fig.savefig(buf, format="png", dpi=dpi, bbox_inches="tight")
    buf.seek(0)
    return buf.read()


def detect_column_roles(df: "pd.DataFrame", target_col: str | None = None) -> dict:
    """Classify each column as numeric, categorical, datetime, or text.

    Returns a dict with keys: numeric, categorical, datetime, text, target, predictor.
    """
    import pandas as pd

    numeric: list[str] = []
    categorical: list[str] = []
    datetime_cols: list[str] = []
    text_cols: list[str] = []

    for col in df.columns:
        dtype = df[col].dtype
        if pd.api.types.is_numeric_dtype(dtype):
            numeric.append(col)
        elif pd.api.types.is_datetime64_any_dtype(dtype):
            datetime_cols.append(col)
        elif pd.api.types.is_object_dtype(dtype):
            unique_ratio = df[col].nunique() / max(len(df), 1)
            if unique_ratio < 0.5:
                categorical.append(col)
            else:
                text_cols.append(col)
        else:
            categorical.append(col)

    predictors = [c for c in numeric if c != target_col]
    return {
        "numeric": numeric,
        "categorical": categorical,
        "datetime": datetime_cols,
        "text": text_cols,
        "target": target_col,
        "predictor": predictors,
    }


def report_text_templates() -> dict:
    """Return a dictionary of English report text templates keyed by section."""
    return {
        "cover_title": "Data Analysis Report",
        "cover_subtitle": "Autonomous Analysis Generated by DA App",
        "data_overview_title": "1. Data Overview",
        "descriptive_title": "2. Descriptive Statistics",
        "visualization_title": "3. Data Visualizations",
        "correlation_title": "4. Correlation Analysis",
        "regression_title": "5. Regression Analysis",
        "hypothesis_title": "6. Hypothesis Testing",
        "conclusion_title": "7. Conclusions & Recommendations",
        "correlation_interpretation": (
            "The correlation matrix above reveals the pairwise linear relationships "
            "between numeric variables. Variables with |r| > 0.7 indicate strong "
            "correlation; 0.3 < |r| < 0.7 indicate moderate correlation; and "
            "|r| < 0.3 indicate weak or negligible correlation."
        ),
        "regression_interpretation": (
            "The OLS regression results show the estimated effect of each predictor "
            "on the target variable. Coefficients with p < 0.05 are statistically "
            "significant. The R-squared value indicates the proportion of variance "
            "in the target explained by the model."
        ),
        "conclusion_template": (
            "Based on the analysis above, the following key findings emerge:\n\n"
            "1. The dataset contains {n_rows} observations and {n_cols} variables.\n"
            "2. {num_numeric} numeric variables and {num_cat} categorical variables "
            "were identified.\n"
            "3. {regression_summary}\n"
            "4. {correlation_summary}\n\n"
            "These findings suggest that further investigation into {key_variables} "
            "may yield actionable insights for decision-making."
        ),
    }
